FROM busybox:1.36
COPY --chmod=0755 bin/rollout-runner-history-collision /usr/local/bin/rollout-runner
COPY cases/history-collision /cases/history-collision
ENTRYPOINT ["/usr/local/bin/rollout-runner"]
