FROM busybox:1.36
COPY --chmod=0755 bin/rollout-runner-history-fixed /usr/local/bin/rollout-runner
COPY cases/history-create /cases/history-create
COPY cases/history-sparse /cases/history-sparse
ENTRYPOINT ["/usr/local/bin/rollout-runner"]
